### ISSUE TITLE
HELP WANTED – Endpoint for Ranked 2.0 & Operation: Solar Raid

### ISSUE THREAD

**Issue by SwiftCODA** [CNDRD/siegeapi#13]
https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/issues/91#issue-1485588198

**Comment by CNDRD** [comment]
Thanks for letting me know about this, i am however dumb enough to not be able to make it work even with all the info that's already in the thread.. 🥲
(Even spent a solid few hours trying to copy, step-by-step, what Daniel has done in r6api.js.. No success there either..)
