### ISSUE TITLE
Auth.get_player_batch(names, uids, platform)

### ISSUE THREAD

**Issue by ghost** [CNDRD/siegeapi#15]
If I call `get_player_batch` with `names` param,could it return a dictionary whose key is `name` like `player[player.name]`? player[player.id] is not easy to use the key for mapping.

**Comment by CNDRD** [comment]
```py
auth = Auth("email", "pw")
players = await auth.get_player_batch(names=["CNDRD", "DiskitoCEO"])
players_by_name = {x.name: x for _, x in players.items()}
```

This will get you exactly what you're after

**Comment by ghost** [comment]
Thank you
