### ISSUE TITLE
Search function?

### ISSUE THREAD

**Issue by Aidan-The-Dev** [CNDRD/siegeapi#16]
Would it be possible to make a search function instead of using the email and password?

**Comment by CNDRD** [comment]
What do you mean? What search function? I am confused

**Comment by Aidan-The-Dev** [comment]
Like uh what r6.tracker.network has instead of getting just your account information a search function to search players would be way better

**Comment by CNDRD** [comment]
But.. you can do that

**Comment by Aidan-The-Dev** [comment]
Oh ignore me im stupid I didnt read I saw email and password and assumed it only allowed you to get your own stats
