### ISSUE TITLE
How can I avoid HTTP 429 situation?

### ISSUE THREAD

**Issue by a361570441** [CNDRD/siegeapi#25]
I have enabled multiple Ubisoft accounts to obtain data on many players. However, in addition to being able to successfully search for players, these accounts now have 429 too many requests for summary and other subsequent steps. It may be that I only use Is it the reason for a normal request request instead of a session conversation?

**Comment by CNDRD** [comment]
Problem we all struggle with when querying a few too many accounts.
The library tries to automatically log you in only when it needs to (by saving the credentials) but it doesn't solve all your problems.
You will need to figure out a way to fix this yourself, that fits your needs.. As we did all
